export const SHOPEE_GET_PRODUCT_RESPONSE = {
  "error": null,
  "error_msg": null,
  "data": {
    "itemid": 233077338,
    "shopid": 20507921,
    "userid": 0,
    "price_max_before_discount": -1,
    "has_lowest_price_guarantee": false,
    "price_before_discount": 0,
    "price_min_before_discount": -1,
    "exclusive_price_info": null,
    "hidden_price_display": null,
    "price_min": 185000000000,
    "price_max": 205000000000,
    "price": 185000000000,
    "stock": 60,
    "discount": null,
    "historical_sold": 291,
    "sold": 3,
    "show_discount": 0,
    "raw_discount": 0,
    "min_purchase_limit": 1,
    "overall_purchase_limit": {
      "order_max_purchase_limit": 0,
      "overall_purchase_limit": null,
      "item_overall_quota": null,
      "start_date": null,
      "end_date": null,
    },
    "pack_size": null,
    "is_live_streaming_price": null,
    "name": "Laptop RAM 4GB Lenovo - Laptop Lenovo 4GB Ram",
    "ctime": 1493062760,
    "item_status": "normal",
    "status": 1,
    "condition": 4,
    "catid": 100644,
    "description":
      "TERPERCAYA - AMAN - BERGARANSI\nBARANG HILANG SAAT KIRIMAN? KAMI GANTI 100%\n\nAKUN RESMI:  twentycell\nSUDAH LEBIH DARI 99000 BINTANG Di Shopee\nSUDAH LEBIH DARI 78.000 FOLLOWERS Di Shopee\nSUDAH LEBIH DARI 100.000 UNIT TERJUAL DI SELURUH INDONESIA\n\nBERGARANSI\nBONUS TAS BARU\nJAMINAN BUKAN REPLIKA!!!\nKUALITAS ORIGINAL!!!\nKAMI MENGUTAMAKAN KUALITAS!!!\nSPESIFIKASI SESUAI!!!\n\nPERHATIAN!!!\n~Bisa Cash, Debit\n~Bisa Kredit Tanpa Kartu Kredit\n~Bisa Credit Card Bunga 0%\n~Gratis Ongkir Hingga Mulai Dari Rp.20.000 ~ Rp.40.000,- Untuk Semua Produk Kami\n~Waspadalah! Penjual Yang Mengatas Namakan Kami / Transaksi Selain Di Aplikasi Shopee\n~Demi Keamanan Bersama\nHarap Transaksi Melalui Shopee\n~Pada Menu Pencarian, Silahkan Ketik twentycell, Dan Lihat Tab Produk / Terlaris\n~Akun Resmi Kami Hanya Twenty Cell / twentycell\n~Akun Tidak Dapat Di Duplikasi\n~Kami Tidak Bertanggung Jawab Atas Pembelian Apapun Selain Dari Twenty Cell\n\nKeuntungan Belanja Disini:\n#Laptop - Original Unit\n#Produk - Sudah Pilihan Terbaik\n#CheckUp - Sebelum Dikirim Kami Cek Dahulu Kondisi Barang\n#Bonus Windows \u0026 Aplikasi\n#Garansi - Kami Memiliki Toko\n#Asuransi - Apabila Terjadi Kehilangan, Uang Akan Diganti Sepenuhnya Oleh Pihak Jasa Pengiriman\n#Packing - 100% Aman dan Telah Lulus Dari System Check-In Oleh Jasa Pengiriman\n#Kesulitan - Dapat Kami Pandu Cara Penggunaannya\n#Tips - Akan Kami Berikan Cara Merawat Produk Setelah Barang Sampai Tujuan\n#Bintang - Akan Mendapatkan Bintang 5 Dari Kami, Bagi Yang Memberikan Bintang 5\n#Bisa Tukar Tambah Dengan Laptop Bekas\n\n\nPacking Dus + Plastik Bubble Tebal, 100% Aman\n\nKELENGKAPAN:\n#Unit + #Batre + #Adaptor / #Charger + #Kabel Power\n#Gratis Tas New\n\nKondisi mesin 100% prima / bagus, fisik bekas lumayan mulus, model bagus, mesin bandel alias kuat, batre bagus, fungsi bagus semua, sudah terinstal Windows 10 dan Aplikasi umum, tinggal pakai.\n\nGaransi 2 Minggu\nHardware / Software\n\n\nSPESIFIKASI:\n-Brand Lenovo 1st in The Laptop's World\n-Processor : Intel Core 2\n-VGA Mobile Intel\n-RAM 4GB\n-Harddisk 160GB\n-Layar 14\" Wide Screen, Jernih Kontras\n-DVD-RW\n-Wifi\n-Port LAN\n-Port USB\n-Port VGA\n-Card Reader\n-Kondisi Mesin Prima / Kuat\n-Keyboard Empuk\n-Touchpad Lancar\n-Speaker Suara Bagus\n-Lampu Ok\n-Batre Bagus\n-Windows 10 dan Aplikasi\n-Baut Masih Segel\n-Merk Lenovo adalah peringkat nomor 1 di dunia yg telah berhasil mengalahkan semua merk laptop lainnya.",
    "is_mart": false,
    "rich_text_description": null,
    "show_shopee_verified_label": true,
    "size_chart": null,
    "reference_item_id": "",
    "brand": "Lenovo  ",
    "item_rating": {
      "rating_star": 4.678947368421053,
      "rating_count": [190, 3, 0, 6, 37, 144],
    },
    "label_ids": [
      47,
      1000211,
      1000544,
      1000246,
      1002299,
      1001657,
      1002471,
      1002640,
      1002688,
      1011707,
      1011732,
      1011737,
      1012004,
      1012616,
      1012619,
      1015112,
      1000375,
      1001035,
      44,
      74,
      1000247,
      1004684,
      1000006,
      1004682,
      1003099,
      22,
      1010928,
      1012456,
      1012792,
      1012791,
      1015287,
      1015281,
      1015280,
      1015288,
      1007093,
      1015767,
    ],
    "attributes": [{
      "name": "Ukuran Layar Laptop",
      "value": "14 inci",
      "id": 100434,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Tipe Laptop",
      "value": "Lainnya",
      "id": 100388,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Produsen Chipset Grafis",
      "value": "Integrated",
      "id": 100409,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Jenis Penyimpanan",
      "value": "HDD",
      "id": 100048,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Sistem Operasi",
      "value": "Windows",
      "id": 100427,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Optical Disk Drive",
      "value": "Ya",
      "id": 100432,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Kondisi",
      "value": "Bekas",
      "id": 100413,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Berat Produk",
      "value": "2kg",
      "id": 100095,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Tipe Panel",
      "value": "Display",
      "id": 100436,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Ports/ Interface",
      "value": "USB, VGA, LAN, Headset/Mic, Dll",
      "id": 100447,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Tipe Prosesor",
      "value": "Intel Core 2 Duo",
      "id": 100460,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Jumlah Core",
      "value": "Intel Core 2 Duo",
      "id": 100930,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Frekuensi CPU",
      "value": "2.4Ghz",
      "id": 100442,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Kapasitas Penyimpanan",
      "value": "160GB",
      "id": 100465,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Kapasitas Baterai",
      "value": "6cell",
      "id": 100272,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Model Laptop",
      "value": "Laptop",
      "id": 100410,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Jenis Garansi",
      "value": "Garansi Toko",
      "id": 100370,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Masa Garansi",
      "value": "2 Weeks",
      "id": 100121,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }, {
      "name": "Dimensi (P x L x T)",
      "value": ".",
      "id": 100942,
      "is_timestamp": false,
      "brand_option": null,
      "val_id": null,
    }],
    "liked": false,
    "liked_count": 2918,
    "cmt_count": 231,
    "flag": 917504,
    "shopee_verified": true,
    "is_adult": false,
    "is_preferred_plus_seller": false,
    "tier_variations": [{
      "name": "Ram",
      "options": ["2GB", "4GB"],
      "images": null,
      "properties": null,
      "type": 0,
      "summed_stocks": null,
    }],
    "bundle_deal_id": 0,
    "can_use_bundle_deal": false,
    "size_chart_info": null,
    "add_on_deal_info": null,
    "bundle_deal_info": null,
    "can_use_wholesale": false,
    "wholesale_tier_list": [],
    "is_group_buy_item": null,
    "group_buy_info": null,
    "welcome_package_type": 0,
    "welcome_package_info": null,
    "tax_code": null,
    "invoice_option": null,
    "complaint_policy": null,
    "wp_eligibility": null,
    "images": [
      "479c93ed6d6a0562ea4717fd976a797f",
      "ff9821a0b138f0e77a0f18d6dae01bbf",
      "c8dc48eb15e2c64971c3fbf4c3900e96",
      "eebdf5965b6204c5a85913e31360950b",
    ],
    "image": "479c93ed6d6a0562ea4717fd976a797f",
    "video_info_list": null,
    "item_type": 0,
    "is_official_shop": false,
    "show_official_shop_label_in_title": false,
    "shop_location": "KOTA JAKARTA UTARA",
    "coin_earn_label": null,
    "cb_option": 0,
    "is_pre_order": false,
    "estimated_days": 2,
    "badge_icon_type": 0,
    "show_free_shipping": false,
    "shipping_icon_type": 0,
    "cod_flag": 0,
    "is_service_by_shopee": false,
    "show_original_guarantee": false,
    "categories": [{
      "catid": 100644,
      "display_name": "Komputer \u0026 Aksesoris",
      "no_sub": false,
      "is_default_subcat": false,
    }, {
      "catid": 101942,
      "display_name": "Laptop",
      "no_sub": true,
      "is_default_subcat": false,
    }],
    "other_stock": 60,
    "item_has_post": false,
    "discount_stock": 0,
    "current_promotion_has_reserve_stock": false,
    "current_promotion_reserved_stock": 0,
    "normal_stock": 60,
    "brand_id": 1146689,
    "is_alcohol_product": false,
    "show_recycling_info": false,
    "coin_info": { "spend_cash_unit": 100000, "coin_earn_items": [] },
    "models": [{
      "itemid": 233077338,
      "status": 1,
      "current_promotion_reserved_stock": 0,
      "name": "4GB",
      "promotionid": 0,
      "price": 205000000000,
      "price_stocks": [{
        "allocated_stock": 0,
        "stock_breakdown_by_location": [{
          "location_id": "IDZ",
          "available_stock": 30,
          "fulfilment_type": 2,
          "address_id": null,
        }],
      }],
      "current_promotion_has_reserve_stock": false,
      "normal_stock": 30,
      "extinfo": {
        "tier_index": [1],
        "group_buy_info": null,
        "is_pre_order": false,
        "estimated_days": 2,
      },
      "price_before_discount": 0,
      "modelid": 46883996588,
      "stock": 30,
      "has_gimmick_tag": false,
    }, {
      "itemid": 233077338,
      "status": 1,
      "current_promotion_reserved_stock": 0,
      "name": "2GB",
      "promotionid": 0,
      "price": 185000000000,
      "price_stocks": [{
        "allocated_stock": 0,
        "stock_breakdown_by_location": [{
          "location_id": "IDZ",
          "available_stock": 30,
          "fulfilment_type": 2,
          "address_id": null,
        }],
      }],
      "current_promotion_has_reserve_stock": false,
      "normal_stock": 30,
      "extinfo": {
        "tier_index": [0],
        "group_buy_info": null,
        "is_pre_order": false,
        "estimated_days": 2,
      },
      "price_before_discount": 0,
      "modelid": 84221197396,
      "stock": 30,
      "has_gimmick_tag": false,
    }],
    "spl_info": {
      "installment_info": null,
      "user_credit_info": null,
      "channel_id": null,
      "show_spl": false,
      "show_spl_lite": false,
    },
    "preview_info": null,
    "fe_categories": [{
      "catid": 11044364,
      "display_name": "Komputer \u0026 Aksesoris",
      "no_sub": false,
      "is_default_subcat": false,
    }, {
      "catid": 11044440,
      "display_name": "Laptop",
      "no_sub": false,
      "is_default_subcat": false,
    }, {
      "catid": 11044444,
      "display_name": "Laptop Konsumer",
      "no_sub": true,
      "is_default_subcat": false,
    }],
    "presale_info": null,
    "show_best_price_guarantee": false,
    "is_cc_installment_payment_eligible": true,
    "is_non_cc_installment_payment_eligible": true,
    "flash_sale": null,
    "upcoming_flash_sale": null,
    "deep_discount": null,
    "has_low_fulfillment_rate": false,
    "is_partial_fulfilled": false,
    "makeups": null,
    "shop_vouchers": [],
    "credit_insurance_data": { "insurance_products": [] },
    "global_sold": 297,
    "is_infant_milk_formula_product": false,
    "should_show_amp_tag": true,
    "sorted_variation_image_index_list": null,
    "lowest_past_price": null,
  },
  "is_indexable": true,
};

export const SHOPEE_GET_PRODUCT_RECOMMENDATION_RESPONS = {
  "bff_meta": null,
  "error": 0,
  "error_msg": null,
  "data": {
    "update_time": 1654828606,
    "version": "1654828606",
    "sections": [{
      "total": 500,
      "key": "dd_main_sec",
      "index": [{
        "data_type": "item",
        "key": "item::6776887467",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::9578235304",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::8415459802",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::4961172837",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::2115798998",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::5141701136",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::13262572396",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::11056619532",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::4422337166",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::6456317749",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::11346256380",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::4492123638",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::633967265",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::4653307963",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::5416927219",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::4256575696",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::2097494770",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::8251655",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::6947286976",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::5651882481",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::6038817012",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::10651577563",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::15268635038",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::10449096868",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::1441562544",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::12208914894",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::3460438504",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::7717071624",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::10384979693",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::2328597199",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::853700747",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::12372852429",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::5419426819",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::4177813471",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::4972401330",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::642660010",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::13918046059",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::7496291104",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::6556347723",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::8873425183",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::12228959236",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::4078575361",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::1186092271",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::4505052460",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::2283419930",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::15949611950",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::1476727723",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::4859099747",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::13230944452",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::5617813933",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::6765077589",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::3433545527",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::14664113762",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::10790168749",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::5853363120",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::17641240606",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::3432470370",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::14607312668",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::8444146015",
        "filtered": null,
        "filtered_dunit": null,
      }, {
        "data_type": "item",
        "key": "item::4661246578",
        "filtered": null,
        "filtered_dunit": null,
      }],
      "data": {
        "item": [{
          "itemid": 6776887467,
          "shopid": 362963333,
          "name":
            "PC Rakitan Custom Sesuai Spek & Budget Gaming,Kantoran,Sekolah,Administrasi",
          "label_ids": [
            1006732,
            22,
            1006900,
          ],
          "image": "71367ad620ebc4fe9daff4008a218a25",
          "images": [
            "71367ad620ebc4fe9daff4008a218a25",
            "217abe85d47ceee63929141e9f2d09d1",
            "83638f535732b05b4cd1f7f2077e43eb",
            "e39446395cb7747bd38301a166b77cbf",
            "7b8846b38de5ff0cbce6237b62b9be42",
          ],
          "currency": "IDR",
          "stock": 4983,
          "status": 1,
          "ctime": 1610910709,
          "sold": 0,
          "historical_sold": 17,
          "liked": false,
          "liked_count": 492,
          "view_count": null,
          "catid": 100644,
          "brand": "",
          "cmt_count": 2,
          "flag": 720896,
          "cb_option": 0,
          "item_status": "normal",
          "price": 50000000000,
          "price_min": 50000000000,
          "price_max": 50000000000,
          "price_min_before_discount": -1,
          "price_max_before_discount": -1,
          "hidden_price_display": null,
          "price_before_discount": 0,
          "has_lowest_price_guarantee": false,
          "show_discount": 0,
          "raw_discount": 0,
          "discount": null,
          "is_category_failed": null,
          "size_chart": null,
          "video_info_list": [],
          "tier_variations": [
            {
              "name": "",
              "options": [
                "",
              ],
              "images": null,
              "properties": [],
              "type": 0,
            },
          ],
          "item_rating": {
            "rating_star": 5,
            "rating_count": [
              2,
              0,
              0,
              0,
              0,
              2,
            ],
            "rcount_with_image": 1,
            "rcount_with_context": 2,
          },
          "item_type": 0,
          "reference_item_id": "",
          "transparent_background_image": "",
          "is_adult": false,
          "badge_icon_type": 0,
          "shopee_verified": false,
          "is_official_shop": false,
          "show_official_shop_label": false,
          "show_shopee_verified_label": false,
          "show_official_shop_label_in_title": false,
          "is_cc_installment_payment_eligible": true,
          "is_non_cc_installment_payment_eligible": false,
          "coin_earn_label": null,
          "show_free_shipping": false,
          "preview_info": null,
          "coin_info": null,
          "exclusive_price_info": null,
          "bundle_deal_id": 0,
          "can_use_bundle_deal": false,
          "bundle_deal_info": null,
          "is_group_buy_item": null,
          "has_group_buy_stock": null,
          "group_buy_info": null,
          "welcome_package_type": 0,
          "welcome_package_info": null,
          "add_on_deal_info": null,
          "can_use_wholesale": false,
          "is_preferred_plus_seller": false,
          "shop_location": "KOTA MEDAN",
          "has_model_with_available_shopee_stock": false,
          "voucher_info": null,
          "is_on_flash_sale": false,
          "spl_installment_tenure": null,
          "is_live_streaming_price": null,
          "shop_name": "suksesmajucomputer",
          "shop_rating": 4.2,
          "is_mart": false,
          "pack_size": null,
          "overlay_image": "",
          "autogen_title": "",
          "autogen_title_id": "",
          "overlay_id": null,
          "is_service_by_shopee": false,
          "flash_sale_stock": 0,
          "info":
            "EXP:WN0,RNK:dd_fgv7_new_user_v42@ID_1654614855:{SCORE:0.040262636},QUE:MIXER_BASELINE_20220428_SwingStrategy_instance_1_swing_v8_ctr_cr,ATP:DEF,QUES:MIXER_BASELINE_20220428_SwingStrategy_instance_1_swing_v8_ctr_cr,REQID:1f8a1b84e10ecf37ef34c4981e53a500%3A02000026985d25bc%3A010000e54bb16181,PID:11,SLTKEY:dd_main_slot_item,SEC:dd_main_sec_00,SECKEY:dd_main_sec,BNDOPT:new_user_experiment_order#control_1,BND:daily_discover_main,USR:nonbuyer_gender_atc_order",
          "data_type": "item",
          "key": "item::6776887467",
          "count": 0,
          "adsid": 0,
          "campaignid": 0,
          "deduction_info": "",
          "video_display_control": 1,
          "deep_discount_skin": null,
          "experiment_info": {
            "image_overlay_exp": {
              "group": "non_login_group",
              "images": null,
            },
            "title_autogen_exp": {
              "group": "non_login_group",
              "title": null,
            },
            "highlight_video_exp": {
              "group": "non_login_group",
            },
            "cod_free_shipping_exp": {
              "group": "non_login_group",
              "should_display_free_shipping": false,
              "should_display_cod": false,
            },
          },
          "relationship_label": "",
          "live_stream_session": {
            "shop_is_live": false,
            "session_id": null,
            "view_cnt": null,
          },
          "new_user_label": false,
          "wp_eligibility": null,
          "platform_voucher": null,
          "rcmd_reason": null,
          "highlight_video": null,
          "search_id": "SwingStrategy_instance_1_swing_v8_ctr_cr",
          "can_use_cod": true,
          "pub_id": "rcmd_dd_main",
          "pub_context_id": "4bb5796f-488d-491e-a9e0-23f626b7042a",
          "friend_relationship_label": "",
          "showing_rs_label": false,
          "showing_friend_rs_label": false,
          "show_flash_sale_label": false,
          "product_banners": null,
          "top_product_label": null,
        }],
        "keyword": null,
        "ads": null,
        "top_product": null,
        "collection": null,
        "item_lite": null,
        "video": null,
        "voucher": null,
        "voucher_detail": null,
        "l1cat": null,
        "collection_lite": null,
        "l2cat": null,
        "shop": null,
        "shop_lite": null,
        "shopcat": null,
        "feed": null,
        "feed_tab": null,
        "stream": null,
        "promotion": null,
        "knode": null,
        "food_item": null,
        "l3cat": null,
      },
      "item_card_type": "",
      "section_meta_data": null,
    }],
    "expire": 1654828606,
    "tab_meta_data": {
      "id": 10,
      "country": "id",
      "name": "Default",
      "start_time": 946656000,
      "end_time": 2145888000,
      "all_tab_config": {
        "display_text": "Semua",
        "tab_image": "8605794b554a56fbd45124ab53f87ca7",
        "text_color": "#ee4d2d",
        "endpoint": {
          "path": "/api/v4/recommend/recommend",
          "fixed_params": [{
            "name": "bundle",
            "value": "daily_discover_main",
            "type": 3,
          }, { "name": "limit", "value": "20", "type": 1 }],
          "params": [
            { "name": "bundle", "value": null, "type": 3 },
            { "name": "offset", "value": null, "type": 1 },
            { "name": "limit", "value": null, "type": 1 },
            { "name": "latitude", "value": null, "type": 2 },
            { "name": "longitude", "value": null, "type": 2 },
            { "name": "city", "value": null, "type": 3 },
            { "name": "district", "value": null, "type": 3 },
            { "name": "friend_visible", "value": null, "type": 1 },
          ],
          "method": "GET",
        },
      },
      "campaign_tabs": [{
        "display_text": "Gratis Ongkir Xtra",
        "pc_image": "f883e1bc7061c56728a8d0e4a99de610",
        "tab_image": "d8bbcb6dbf922e66dd4d8f52dae0df8a",
        "algo_type": 26,
        "text_color": "#ee4d2d",
        "product_label": 1000006,
        "id": 33876,
        "order": 0,
        "endpoint": null,
      }, {
        "display_text": "Cashback XTRA",
        "pc_image": "863a7113e8965ad5268d304b01250ebf",
        "tab_image": "5de66ecb9383b4a3057c814d7c17d69d",
        "algo_type": 26,
        "text_color": "#ee4d2d",
        "product_label": 1000246,
        "id": 33877,
        "order": 1,
        "endpoint": null,
      }, {
        "display_text": "Bayar Di Tempat",
        "pc_image": "121d1a549c3ba21bf3964a5a7c3d86e9",
        "tab_image": "418589a5bdef786de52bbaaa342d58a6",
        "algo_type": 26,
        "text_color": "#ee4d2d",
        "product_label": 1000031,
        "id": 33878,
        "order": 2,
        "endpoint": null,
      }],
      "mtime": null,
      "operator": null,
      "tabs": null,
      "should_hide_tabs": false,
    },
    "misc_info": null,
    "realtime_meta_data": null,
    "user_meta_data": { "is_new_user": true },
  },
};

export const SHOPEE_GET_PRODUCT_SEARCH_RESPONSE = {
  "bff_meta": null,
  "error": null,
  "error_msg": null,
  "reserved_keyword": null,
  "suggestion_algorithm": null,
  "algorithm":
    "eyJzZWFyY2giOiIwLmEuNTE0N0BVU1ZGTUVVVUlXVEZSWVhOSVBRUEVIS1JFWU9ORUpLVUVSVlowV0ZUWUdWMUVUT1BEWVpBRVNFRzJaSjNQUThaQzg4R08xNDcifQ==",
  "total_count": 3107,
  "nomore": false,
  "items": [{
    "item_basic": {
      "itemid": 11719461426,
      "shopid": 295848216,
      "name":
        '20-28" Koper Cabin Koper Bagasi Koper Wanita Koper Pria Import Suitcase Luggage PK-A006',
      "label_ids": [
        1007524,
        1010471,
        1003097,
        1000006,
        1001019,
        1008870,
        1010462,
        1010928,
        1011715,
        1011720,
        1011725,
        1011751,
        1011752,
        1011712,
        1002164,
        1012446,
        1012791,
        1015247,
      ],
      "image": "36fd61e34a1bf8cd38e96031df337af9",
      "images": [
        "36fd61e34a1bf8cd38e96031df337af9",
        "5dadfb3a4171e5acc47d3ad202a4ab20",
        "ef7ae84f3a58d5103619504e78222ce7",
        "f698357e691196fb3b18c0ff250ee553",
        "8301244fb128054e7257ee0c2d0e3c1b",
        "2e2bcd1a350e2a9ecfbd22463fd2b76d",
        "cab186ffcb39ec9c5960b6f2539b74be",
      ],
      "currency": "IDR",
      "stock": 1742,
      "status": 1,
      "ctime": 1626667336,
      "sold": 296,
      "historical_sold": 643,
      "liked": false,
      "liked_count": 5145,
      "view_count": null,
      "catid": 100015,
      "brand": "",
      "cmt_count": 324,
      "flag": 720896,
      "cb_option": 0,
      "item_status": "normal",
      "price": 75800000000,
      "price_min": 75800000000,
      "price_max": 112500000000,
      "price_min_before_discount": 109375000000,
      "price_max_before_discount": 170625000000,
      "hidden_price_display": null,
      "price_before_discount": 109375000000,
      "has_lowest_price_guarantee": false,
      "show_discount": 34,
      "raw_discount": 34,
      "discount": "34%",
      "is_category_failed": null,
      "size_chart": "",
      "video_info_list": [
        {
          "video_id": "1c09a035975744af17cb37383b56e959",
          "thumb_url": "86975cb76d0c72ab1a57e3ef64f5f2a3",
          "duration": 59,
          "version": 2,
          "vid": "sg_f498fff2-f586-4a68-af8b-12ba9fa6a62d_000130",
          "formats": [
            {
              "format": 1600008,
              "defn": "V720P",
              "profile": "MP4",
              "path": "c3/98934353/105/AnoyY3YAZNCmZAAhbAEGAEY.mp4",
              "url": "",
              "width": 640,
              "height": 368,
            },
          ],
          "default_format": {
            "format": 600001,
            "defn": "ORI",
            "profile": "MP4",
            "path": "",
            "url":
              "http://play-aka.vod.shopee.com/c3/98934353/105/Anoy=wIANF-mZAAhjQENAEY.mp4",
            "width": 640,
            "height": 368,
          },
        },
      ],
      "tier_variations": [
        {
          "name": "Warna",
          "options": [
            "Black",
            "Pink",
            "Yellow",
            "Red",
            "Grey",
            "Silver",
            "Blue",
          ],
          "images": [
            "2de12fdbd0c5e83b8decfcad93fc1dfa",
            "f698357e691196fb3b18c0ff250ee553",
            "8301244fb128054e7257ee0c2d0e3c1b",
            "20d5d9044ce72c08916fd011e08bb134",
            "2e2bcd1a350e2a9ecfbd22463fd2b76d",
            "b94e91f781dfe9117555bf7244b1581f",
            "5ab3a207757f24af3325dd554f386d84",
          ],
          "properties": [],
          "type": 0,
        },
        {
          "name": "Size",
          "options": [
            "20",
            "22",
            "24",
            "26",
            "28",
          ],
          "images": null,
          "properties": [],
          "type": 0,
        },
      ],
      "item_rating": {
        "rating_star": 4.888888888888889,
        "rating_count": [
          324,
          1,
          1,
          3,
          23,
          296,
        ],
        "rcount_with_context": 115,
        "rcount_with_image": 110,
      },
      "item_type": 0,
      "reference_item_id": "",
      "transparent_background_image": "",
      "is_adult": false,
      "badge_icon_type": 0,
      "shopee_verified": true,
      "is_official_shop": false,
      "show_official_shop_label": false,
      "show_shopee_verified_label": true,
      "show_official_shop_label_in_title": false,
      "is_cc_installment_payment_eligible": true,
      "is_non_cc_installment_payment_eligible": false,
      "coin_earn_label": null,
      "show_free_shipping": false,
      "preview_info": null,
      "coin_info": null,
      "exclusive_price_info": null,
      "bundle_deal_id": 0,
      "can_use_bundle_deal": false,
      "bundle_deal_info": null,
      "is_group_buy_item": null,
      "has_group_buy_stock": null,
      "group_buy_info": null,
      "welcome_package_type": 0,
      "welcome_package_info": null,
      "add_on_deal_info": null,
      "can_use_wholesale": false,
      "is_preferred_plus_seller": true,
      "shop_location": "KOTA JAKARTA UTARA",
      "has_model_with_available_shopee_stock": false,
      "voucher_info": null,
      "can_use_cod": true,
      "is_on_flash_sale": false,
      "spl_installment_tenure": null,
      "is_live_streaming_price": null,
      "is_mart": false,
      "pack_size": null,
      "deep_discount_skin": null,
      "is_service_by_shopee": false,
    },
    "adsid": 92527881,
    "campaignid": 60585316,
    "distance": null,
    "match_type": 0,
    "ads_keyword": "wkdaelpmissisiht",
    "deduction_info":
      "Y3MrY1lnQUFBQUJvV1hwYTgXWTJsaBGpCyoL4RO9lLuDfAmH2ErAcZOd5EYSi7TBHGGO5WzUUmlmK8ZIGJJcRPmXtp7VQB5mgkHO9DCRJr99Y9/qy8Wd4emlAGhm3/rOiumTnVrLaaxOBXA+f+X2/w==",
    "collection_id": null,
    "display_name": null,
    "campaign_stock": null,
    "json_data":
      "SARoBnGfQE3PK9aeP3kAAAAATEGLP4gBBpAB1+iKlQaQAwLIDATQDAHYDATpDC/Yk7t6Osw/",
    "tracking_info": null,
    "itemid": 11719461426,
    "shopid": 295848216,
    "algo_image": null,
    "fe_flags": null,
    "item_type": 1,
    "foody_item": null,
    "search_item_tracking":
      '{"is_ads":true,"groupid":0,"fe_flags":"{}","item_type":1,"biz_json":"","merge_rank":0,"shuffle_rank":0}',
    "bff_item_tracking":
      '{"label_ids":[1007524,1010471,1003097,1000006,1001019,1008870,1010462,1010928,1011715,1011720,1011725,1011751,1011752,1011712,1002164,1012446,1012791,1015247],"is_on_flash_sale":false,"is_liked":false,"with_video":true,"is_dp_mirror_sku":false,"image_position":null}',
    "personalized_labels": null,
    "biz_json": null,
  }],
  "price_adjust": null,
  "adjust": { "count": 3007 },
  "total_ads_count": 100,
  "hint_keywords": null,
  "show_disclaimer": false,
  "json_data":
    "Cjl8c2lnPWFsZ289c2xvdD1pbmNyZWFzZWQ7c2NoLmRlZHVwbGljYXRlPWRlZmF1bHQ7fHJ8MTY4MXxSjwFiZmYtc2VhcmNoX2lkX3NnNl8xMC4xMzEuMTEzLjEzMV97MWY4YTFiODRlMTBmMmM0YzJjOTMzOGM4YmFiYjJmMDA6MDEwMDAwZTIwOWI3ZTgwNzowMDAwMDA0OGI3OWJlMWMzfV9rOHMtd29ya2VyLXNnNi1saXZlLTIzMDYuc2hvcGVlbW9iaWxlLmNvbZAB1+iKlQY=",
  "query_rewrite": {
    "fe_query_write_status": 0,
    "rewrite_keyword": null,
    "hint_keywords": null,
    "ori_keyword": "koper",
    "ori_total_count": 3007,
    "rewrite_type": null,
  },
  "disclaimer_infos": [],
  "need_next_search": true,
  "low_result": {
    "triggered": false,
    "scenarios": null,
    "total_organic_count": 3007,
    "pre_lrp_total_organic_count": 3007,
  },
  "autoplay_info": null,
  "food_item_info": { "total_count": 0 },
  "search_tracking":
    '{"algorithm":"eyJzZWFyY2giOiIwLmEuNTE0N0BVU1ZGTUVVVUlXVEZSWVhOSVBRUEVIS1JFWU9ORUpLVUVSVlowV0ZUWUdWMUVUT1BEWVpBRVNFRzJaSjNQUThaQzg4R08xNDcifQ==","low_result":{"triggered":false,"total_organic_count":3007,"pre_lrp_total_organic_count":3007},"total_ads_count":100,"total_count":3107,"query_expansion_info":{"expansion_type":8},"request_id":"bff-search_id_sg6_10.131.113.131_{1f8a1b84e10f2c4c2c9338c8babb2f00:010000e209b7e807:00000048b79be1c3}_k8s-worker-sg6-live-2306.shopeemobile.com","version_tracking":"{\\"rank\\":\\"{\\\\\\"code\\\\\\":\\\\\\"0.0.11-24\\\\\\",\\\\\\"config\\\\\\":\\\\\\"\\\\\\"}\\",\\"qp\\":\\"{\\\\\\"Code\\\\\\":\\\\\\"9fa4904\\\\\\",\\\\\\"Config\\\\\\":\\\\\\"others=default;\\\\\\"}\\",\\"algo_ss\\":\\"{\\\\\\"Code\\\\\\":\\\\\\"bd2f9d3\\\\\\",\\\\\\"Config\\\\\\":\\\\\\"others=default;plugin=1654743268;\\\\\\"}\\",\\"search_server\\":\\"{\\\\\\"Code\\\\\\":\\\\\\"search-v1.94.2-warranty\\\\\\",\\\\\\"Config\\\\\\":\\\\\\"others=default;\\\\\\"}\\",\\"es_proxy\\":\\"{\\\\\\"Code\\\\\\":\\\\\\"f684912\\\\\\",\\\\\\"Config\\\\\\":\\\\\\"others=default;\\\\\\"}\\"}"}',
  "search_sessionid": null,
  "batch_size": 60,
  "search_item_bff_tracking":
    '{"ab_test_sign":"0.a.5148@UW0","version_tracking":"{\\"Code\\":\\"55b041e\\",\\"Config\\":\\"m_cnf=9;others=default;\\"}"}',
  "user_info": { "user_type": null },
};
