name: Flat

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
    #- cron: '0 9 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Fetch Shopee Trending Keyword Data
        uses: githubocto/flat@v3
        with:
          http_url: https://raw.githubusercontent.com/siral-id/shopee-id-trends/main/shopee_trends.json
          downloaded_filename: shopee_trends.json
            # postprocess: trends-to-keywords.ts

  postprocess:
    runs-on: ubuntu-latest
    needs: scheduled
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Checkout code
        uses: actions/checkout@master

      - name: Fetch All Daily Products
        run: deno run -A --unstable daily-products.ts

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          force: true
