name: Flat

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
    #- cron: '0 9 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Fetch Shopee Trending Keyword Data
        uses: githubocto/flat@v3
        with:
          http_url: https://github.com/siral-id/shopee-id-trends/blob/main/shopee_trends.json 
          downloaded_filename: shopee_trends.json
          postprocess: ./postprocess/trends-to-keywords.ts

      - name: Fetch Shopee Daily Recommended Product
        uses: githubocto/flat@v3
        with:
          http_url: https://shopee.co.id/api/v4/recommend/recommend?bundle=daily_discover_main&item_card=3&limit=60&offset=0
          downloaded_filename: daily_products.json
          postprocess: ./postprocess/daily-products.ts
