name: Scrap

  on:
    push:
      branches:
        - main
    workflow_dispatch:
    schedule:
      - cron: "*/5 * * * *"

  jobs:
    execute:
      runs-on: ubuntu-latest
      needs: scheduled
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: "3.8"

        - uses: snok/install-poetry@v1
        - name: Install Dependencies
          run: poetry install

        - name: Checkout code
          uses: actions/checkout@master

        - name: Fetch All Daily Products
          run: python src/siral_scrapers/services/tokopedia_trends.py

        - name: Commit & Push changes
          uses: actions-js/push@master
          with:
            github_token: ${{ secrets.GH_TOKEN }}
            branch: main
            force: true
