name: Trending Products

on:
  issues:
    types: [opened]

  workflow_dispatch:
  
jobs:
  trending_product_0:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: populate trending products
        run: |
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
            deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/trending_products.ts '${{ github.event.issue.body }}' '${{matrix.node}}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_0 }}

      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Trending Product data successfully populated and forwarded backs. Closing issue...

  trending_product_1:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: populate trending products
        run: |
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
            deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/trending_products.ts '${{ github.event.issue.body }}' '${{matrix.node}}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_1 }}

      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Trending Product data successfully populated and forwarded backs. Closing issue...

  trending_product_2:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: populate trending products
        run: |
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
            deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/trending_products.ts '${{ github.event.issue.body }}' '${{matrix.node}}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_2 }}

      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Trending Product data successfully populated and forwarded backs. Closing issue...

  trending_product_3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: populate trending products
        run: |
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
            deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/trending_products.ts '${{ github.event.issue.body }}' '${{matrix.node}}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_3 }}

      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Trending Product data successfully populated and forwarded backs. Closing issue...

  trending_product_4:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: populate trending products
        run: |
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
            deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/trending_products.ts '${{ github.event.issue.body }}' '${{matrix.node}}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_4 }}

      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Trending Product data successfully populated and forwarded backs. Closing issue...

  trending_product_5:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: populate trending products
        run: |
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
            deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/trending_products.ts '${{ github.event.issue.body }}' '${{matrix.node}}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_5 }}

      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Trending Product data successfully populated and forwarded backs. Closing issue...

  trending_product_6:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: populate trending products
        run: |
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
            deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/trending_products.ts '${{ github.event.issue.body }}' '${{matrix.node}}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_6 }}

      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Trending Product data successfully populated and forwarded backs. Closing issue...

  trending_product_7:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: populate trending products
        run: |
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
            deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/trending_products.ts '${{ github.event.issue.body }}' '${{matrix.node}}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_7 }}

      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Trending Product data successfully populated and forwarded backs. Closing issue...

  trending_product_8:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: populate trending products
        run: |
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
            deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/trending_products.ts '${{ github.event.issue.body }}' '${{matrix.node}}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_8 }}

      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Trending Product data successfully populated and forwarded backs. Closing issue...

  trending_product_9:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: populate trending products
        run: |
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
            deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/trending_products.ts '${{ github.event.issue.body }}' '${{matrix.node}}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_9 }}

      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Trending Product data successfully populated and forwarded backs. Closing issue...
