name: Trending Products

on:
  issues:
    types: [opened]

  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        node: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    runs-on: ubuntu-latest

    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
          
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        
      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: populate trending products
        run: |
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
            deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/trending_products.ts '${{ github.event.issue.body }}' '${{matrix.node}}'
        env:
          GH_TOKEN: ${{ secrets[format('GH_TOKEN_{0}', matrix.node)] }}

      - if: startsWith(github.event.issue.title, 'FORWARD_TREND') == true
        name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Trending Product data successfully populated and forwarded backs. Closing issue...
